#!/usr/bin/env python3

from __future__ import annotations

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    match = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not match:
        raise ValueError("Expected YAML frontmatter delimited by ---")

    raw_meta, body = match.groups()
    meta: dict[str, str] = {}

    for line in raw_meta.splitlines():
        if not line.strip():
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip().strip('"')

    return meta, body


def render_frontmatter(meta: dict[str, str], allowed_keys: list[str]) -> str:
    lines = ["---"]
    for key in allowed_keys:
        value = meta.get(key)
        if value is None:
            continue
        if key == "user-invocable":
            lines.append(f"{key}: {value}")
        else:
            lines.append(f'{key}: "{value}"')
    lines.append("---")
    return "\n".join(lines)


def build_copilot_wrapper(skill_name: str, description: str, body: str, source_path: Path) -> str:
    return (
        f"# {skill_name}\n\n"
        f"Generated from `{source_path.as_posix()}`. Do not edit this file directly.\n\n"
        f"{description}\n\n"
        "Apply these instructions when using this workflow in GitHub Copilot or Copilot CLI.\n\n"
        f"{body.lstrip()}"
    )


def generate_skill(skill_dir: Path) -> None:
    base_path = skill_dir / "base.md"
    meta, body = parse_frontmatter(base_path.read_text())
    skill_name = meta["name"]
    description = meta["description"]

    generated_note = (
        f"<!-- Generated from {base_path.relative_to(ROOT).as_posix()}. Do not edit directly. -->\n\n"
    )

    claude_text = (
        render_frontmatter(
            {
                "name": skill_name,
                "description": description,
                "user-invocable": meta.get("user-invocable", "true"),
            },
            ["name", "description", "user-invocable"],
        )
        + "\n\n"
        + generated_note
        + body.lstrip()
    )

    codex_text = (
        render_frontmatter(
            {
                "name": skill_name,
                "description": description,
            },
            ["name", "description"],
        )
        + "\n\n"
        + generated_note
        + body.lstrip()
    )

    copilot_text = build_copilot_wrapper(
        skill_name=skill_name,
        description=description,
        body=body,
        source_path=base_path.relative_to(ROOT),
    )

    outputs = {
        ROOT / f"{skill_name}.md": claude_text,
        skill_dir / "claude.md": claude_text,
        skill_dir / "codex" / "SKILL.md": codex_text,
        skill_dir / "copilot" / "AGENTS.md": copilot_text,
        skill_dir / "copilot" / ".github" / "copilot-instructions.md": copilot_text,
    }

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def main() -> None:
    for candidate in sorted(ROOT.iterdir()):
        if not candidate.is_dir() or candidate.name.startswith("."):
            continue
        base_path = candidate / "base.md"
        if base_path.exists():
            generate_skill(candidate)


if __name__ == "__main__":
    main()
